### ISSUE TITLE
Retriable doesn't aggregate exceptions.

### ISSUE THREAD

**Issue by MaximRouiller** [endjin/Endjin.Retry#1]
For code : 

``` csharp
var exceptionGenerator = new ExceptionGenerator();
Retriable.Retry(exceptionGenerator.GenerateNotImplementedException);
```

**Expected:** AggregateException that returns all exceptions that were generated during all the retries if they all fail.

**Result:** Only return the last exception.

**Explanation:** When calling services, sometimes the first exception could hold information as to what happened. If my retries are too close together, the last exception could only be about me pounding it. The first exception might actually hold why it needed to retry in the first place. 

If it's not "by default" it should be relatively easy to just toggle: "always return aggregated exceptions".

**Comment by mwadams** [comment]
Are you aware that the RetryStrategy exposes a property called Exception, which gives you an aggregate exception containing all the exceptions thrown during the course of the retry attempt?

We decided not to throw that AE, but instead to throw the last exception that failed, in order that the signature (including any documented exceptions) should not be changed by wrapping the method call in a Retriable.Retry().

If you want the behaviour you suggest, you could add an overload which throws the AggregateException, but it should be made clear (preferably in the method name) that this will be signature-mutating.

Pull requests are more than welcome!
