### ISSUE TITLE
Make Endjin.Retry .NET standard compliant

### ISSUE THREAD

**Issue by Kennethtruyers** [endjin/Endjin.Retry#3]
I'd be happy to provide a PR for this if you're still maintaining this library

**Comment by HowardvanRooijen** [comment]
Hi,

We're still maintaining, although I think we have a .NET Standard version in our internal repo. I'll chat to @mwadams and see if we can release a new version with those bits.

**Comment by mwadams** [comment]
Absolutely. What netstandard version (s) would you like to publish? Internally, we are using netstandard 2.0

**Comment by Kennethtruyers** [comment]
Hi, I think indeed netstandard 2.0 would be sufficient

**Comment by lahma** [comment]
@mwadams I see that the repo already has the netstandard2.0 bits. Could you please push a release to NuGet so we all could enjoy it?

**Comment by mwadams** [comment]
@lahma that sounds like a good idea! I'll see what I can do.

**Comment by lahma** [comment]
@mwadams happy new year! Any chance of getting a fresh release to NuGet? 🙂

**Comment by HowardvanRooijen** [comment]
We're working on it! Shouldn't be long!

**Comment by HowardvanRooijen** [comment]
We've actually published a new library (along with a lot more of our internal IP) over at a new GitHub org. The latest version of Endjin.Retry is now https://github.com/corvus-dotnet/Corvus.Retry
