### ISSUE TITLE
Make Endjin.Rtry mockable for unit test purposes

### ISSUE THREAD

**Issue by Kennethtruyers** [endjin/Endjin.Retry#4]
We have been using a very thin layer on top of Endjin.Retry for a while now to be able to inject it into classes that needed for unit testing purposes.

I'd be willing to embed this thin layer directly into Endjin.Retry and provide a PR

**Comment by HowardvanRooijen** [comment]
I'd be interested to see how you've added a mockable layer and what you think you need to achieve that. I don't think we've ever needed to mock Retriable, mainly because we see that as an internal implementation detail, and we mock at the level of the method that does the retrying. /cc @mwadams

**Comment by mwadams** [comment]
Have you got a gist that illustrates your changes?

**Comment by Kennethtruyers** [comment]
Yeah sure: https://gist.github.com/Kennethtruyers/d61ac5cec64dc57e03dae67f0ce6b924

It does a couple of things:
* Adds a factory for predefined strategies
* Creates an interface you can inject into a class
* Adds some extension methods to the IRetry interface

**Comment by mwadams** [comment]
@Kennethtruyers - can you show me how you are using this; how does mocking this help you in your specific test? I understand the desire for some "standard" methods with useful default combinations, but I'm struggling with "mocking" (if the "mock" doesn't actually execute the underlying code, then what are you testing?). I'm probably being dim - I haven't had my coffee yet.

**Comment by Kennethtruyers** [comment]
To be honest, I think I'm the one being dim here. 
This code has always been around in our codebase and we've been using it without thinking. 

Please ignore the mocking part of this, I just realized it's not necessary at all. Apologies for the waste of time. Thanks for making me realize we're doing something useless :-)

**Comment by mwadams** [comment]
Thinking about stuff is never a waste of time :)

I've pushed up the netstandard2.0 build, but it isn't on Nuget yet.

**Comment by HowardvanRooijen** [comment]
We were scratching our heads a little - we've been using it for 5+ years and we've never mocked it - and we were wondering if we'd been missing out on something all this time! Glad you're using it tho - it's nice to hear some of these bits of code we've OSS'd are getting used.

**Comment by Kennethtruyers** [comment]
It would be nice to have those utility methods in EndjinRetrySource though as well as some strategy with the predicate.

**Comment by swissarmykirpan** [comment]
@idg10 I think this was something our good friend Ian introduced!

**Comment by mwadams** [comment]
Aha! Ian's is always good advice to take :)

**Comment by idg10** [comment]
Yes, I'm pretty sure I introduced `Endjin.Retry` to the project in question. (I don't think the thin layer of mockability was mine, although I can't be 100% sure - I did an awful lot in a very short length of time back then... If it was then I'm afraid I can't remember what motivated me to do it.)

**Comment by Kennethtruyers** [comment]
No idea where it came from to be honest. ¯\_(ツ)_/¯

Common sense tells me we don't need it, so I'm going to get rid of it on our end.

Could we have a look to see if we can introduce the convenience methods in some way though? Doesn't have to be this way, but would be nice to have them inside the library. If you want, I can do a proposal PR and we can discuss from there

**Comment by HowardvanRooijen** [comment]
We've actually published a new library (along with a lot more of our internal IP) over at a new GitHub org. The latest version of Endjin.Retry is now https://github.com/corvus-dotnet/Corvus.Retry
